# Generated by Django 4.1.6 on 2023-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gamedata_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='regra',
            name='rule_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
