# Generated by Django 4.1.6 on 2023-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_regra_rule_field_alter_gamedata_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
